// LOGIN ACTION TYPES
export const LOGIN_ACTION_SEND = 'LOGIN_ACTION_SEND';
export const LOGIN_ACTION_RECEIVED = 'LOGIN_ACTION_RECEIVED';
export const USER_LOGIN_DATA = 'USER_LOGIN_DATA';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const LOGIN_ERROR_SHOWN = 'LOGIN_ERROR_SHOWN';

//USER ACTION TYPES
export const USER_GET_FILES = 'USER_GET_FILES';
export const USER_GOT_FILES = 'USER_GOT_FILES';
export const USER_DETAILS = 'USER_DETAILS';
export const USER_ERROR = 'USER_ERROR';
export const USER_ERROR_SHOWN = 'USER_ERROR_SHOWN';
export const USER_ALL_FILES = 'USER_ALL_FILES';
export const USER_GET_FILE_CONTENT = 'USER_GET_FILE_CONTENT';
export const USER_GOT_FILE_CONTENT = 'USER_GOT_FILE_CONTENT';
export const USER_FILE_CONTENT = 'USER_FILE_CONTENT';
export const USER_UPLOADING_FILE = 'USER_UPLOADING_FILE';
export const USER_UPLOADED_FILE = 'USER_UPLOADED_FILE';
export const USER_UPLOAD_FILE = 'USER_UPLOAD_FILE';
export const USER_FILE_RENAMING = 'USER_FILE_RENAMING';
export const USER_FILE_RENAMED = 'USER_FILE_RENAMED';
export const USER_FILE_RENAME = 'USER_FILE_RENAME';
export const USER_CHANGE_SELECTED_FILE_NAME = 'USER_CHANGE_SELECTED_FILE_NAME';
export const USER_DELETING_FILE = 'USER_DELETING_FILE';
export const USER_DELETED_FILE = 'USER_DELETED_FILE';
export const USER_DELETE_FILE = 'USER_DELETE_FILE';
export const USER_FILE_STATUS = 'USER_FILE_STATUS';
export const USER_CHANGING_FILE_STATUS = 'USER_CHANGING_FILE_STATUS';
export const USER_CHANGED_FILE_STATUS = 'USER_CHANGED_FILE_STATUS';
