// LOGIN ACTION TYPES
export const LOGIN_ACTION_SEND = "LOGIN_ACTION_SEND";
export const LOGIN_ACTION_RECEIVED = "LOGIN_ACTION_RECEIVED";
export const USER_LOGIN_DATA = "USER_LOGIN_DATA";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const LOGIN_ERROR_SHOWN = "LOGIN_ERROR_SHOWN";
