// LOGIN ACTION TYPES
export const LOGIN_ACTION_SEND = 'LOGIN_ACTION_SEND';
export const LOGIN_ACTION_RECEIVED = 'LOGIN_ACTION_RECEIVED';
export const USER_LOGIN_DATA = 'USER_LOGIN_DATA';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const LOGIN_ERROR_SHOWN = 'LOGIN_ERROR_SHOWN';

//USER ACTION TYPES
export const USER_GET_FILES = 'USER_GET_FILES';
export const USER_GOT_FILES = 'USER_GOT_FILES';
export const USER_DETAILS = 'USER_DETAILS';
export const USER_ERROR = 'USER_ERROR';
export const USER_ERROR_SHOWN = 'USER_ERROR_SHOWN';
export const USER_ALL_FILES = 'USER_ALL_FILES';
